# dev.tfvars -- generated by pipeline-automator scaffold (project init)
# Concrete input values for the leadouts_test pipeline in the
# dev environment. Commit this file. Do NOT put secrets here --
# credentials come from AWS_PROFILE / environment, never from tfvars.

aws_region   = "eu-central-1"
environment  = "dev"
data_product = "leadouts_test"

bucket_names = {
  raw          = "raw"
  preprocessed = "preprocessed"
  processed    = "processed"
  scripts      = "scripts"
}

tags = {
  DataProduct = "leadouts_test"
  Project     = "leadouts_test"
  Environment = "dev"
  ManagedBy   = "terraform"
}
