# main.tf -- generated by pipeline-automator scaffold (project init)
# Root module for the leadouts_test data pipeline.
#
# The ETL jobs and their triggers between the AMEND:JOBS markers are rebuilt
# from the job specs and contracts by `engineering-automation generate
# create-job` and `generate codegen`. Do not remove the markers -- the sync
# targets them -- and do not edit between them: the next sync replaces it.

locals {
  name_prefix   = "${var.data_product}-${var.environment}"
  bucket_prefix = replace(lower(local.name_prefix), "_", "-")
}

# ---------------------------------------------------------------------------
# Foundational, project-wide resources (created once at project init)
# ---------------------------------------------------------------------------

module "s3" {
  source = "./modules/s3"

  name_prefix                        = local.bucket_prefix
  environment                        = var.environment
  bucket_names                       = var.bucket_names
  lifecycle_rules_enabled            = var.lifecycle_rules_enabled
  noncurrent_version_expiration_days = var.noncurrent_version_expiration_days
  tags                               = var.tags
}

module "iam" {
  source = "./modules/iam"

  name_prefix             = local.name_prefix
  environment             = var.environment
  raw_bucket_arn          = module.s3.bucket_arns["raw"]
  preprocessed_bucket_arn = module.s3.bucket_arns["preprocessed"]
  processed_bucket_arn    = module.s3.bucket_arns["processed"]
  scripts_bucket_arn      = module.s3.bucket_arns["scripts"]
  tags                    = var.tags
}

module "glue" {
  source = "./modules/glue"

  name_prefix         = local.name_prefix
  environment         = var.environment
  role_arn            = module.iam.glue_execution_role_arn
  scripts_bucket_name = module.s3.bucket_names["scripts"]
  tags                = var.tags

  # ---------------------------------------------------------------------------
  # BEGIN ETL jobs and triggers (managed by engineering-automation -- do not edit by hand)
  # >>> AMEND:JOBS
  jobs = {
    prepare_leadouts_data = {
      glue = {
        number_of_workers = 2
        worker_type       = "G.1X"
      }
      arguments = {
        END_DATE                     = "2026-01-01"
        OUTPUT_PATH                  = "s3://${module.s3.bucket_names["preprocessed"]}/prepared_leadouts_data/"
        PROCESSING_TYPE              = "backfill"
        RAW_LEADOUTS_DATA_INPUT_PATH = "s3://${module.s3.bucket_names["raw"]}/raw_leadouts_data/"
        START_DATE                   = "2026-01-01"
      }
    }
  }

  scheduled_triggers = {}

  conditional_triggers = {}
  # <<< AMEND:JOBS
  # END ETL jobs and triggers
  # ---------------------------------------------------------------------------
}
