# outputs.tf -- generated by pipeline-automator scaffold (project init)
# Project-wide outputs for the leadouts_test data pipeline.

output "bucket_arns" {
  description = "ARNs of all medallion and scripts S3 buckets for leadouts_test."
  value       = module.s3.bucket_arns
}

output "bucket_names" {
  description = "Names of all medallion and scripts S3 buckets for leadouts_test."
  value       = module.s3.bucket_names
}

output "scripts_bucket" {
  description = "Name of the S3 bucket the deploy job uploads the shared zip and job scripts to."
  value       = module.s3.bucket_names["scripts"]
}

output "glue_execution_role_arn" {
  description = "ARN of the IAM role assumed by Glue jobs in leadouts_test."
  value       = module.iam.glue_execution_role_arn
}

output "glue_job_names" {
  description = "Map of ETL job key to full Glue job name for leadouts_test."
  value       = module.glue.job_names
}
